In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
df = pd.read_csv("../data/raw/amazon_ecommerce_1M.csv")

In [11]:
df.shape

(1000000, 20)

In [12]:
df = df.sample(n=20000, random_state=42)

In [13]:
df.shape

(20000, 20)

In [14]:
df.head()

,user_id,product_id,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_id,seller_rating,purchase_date,shipping_time_days,location,device,payment_method,is_returned,delivery_status
987231,U907645,P13100,Sports,Cycling,Nike,13307.41,24.89,9995.09,3.2,26,308,S4473,3.5,2025-08-28,4,Mumbai,Tablet,UPI,True,Returned
79954,U995373,P11820,Electronics,Headphones,Samsung,5464.82,15.70,4606.69,3.1,5,453,S1390,2.7,2025-10-05,4,Mumbai,Tablet,Cash on Delivery,False,Delayed
567130,U565186,P25469,Beauty,Makeup,Lenovo,3437.74,45.41,1876.51,3.7,41,222,S4525,3.5,2025-10-29,2,Hyderabad,Web,Debit Card,False,Delayed
500891,U338654,P96278,Home,Kitchen,H&M,7754.11,14.21,6652.29,4.1,128,479,S8223,2.9,2024-05-08,4,Hyderabad,Tablet,UPI,False,In Transit
55399,U351028,P20410,Clothing,Men,Apple,967.17,30.44,672.76,3.9,18,471,S3841,3.3,2025-04-06,5,Delhi,Mobile App,Credit Card,False,Delayed

In [15]:
df.columns

Index(['user_id', 'product_id', 'category', 'subcategory', 'brand', 'price',
       'discount', 'final_price', 'rating', 'review_count', 'stock',
       'seller_id', 'seller_rating', 'purchase_date', 'shipping_time_days',
       'location', 'device', 'payment_method', 'is_returned',
       'delivery_status'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
Index: 20000 entries, 987231 to 809896
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             20000 non-null  str
 1   product_id          20000 non-null  str
 2   category            20000 non-null  str
 3   subcategory         20000 non-null  str
 4   brand               20000 non-null  str
 5   price               20000 non-null  float64
 6   discount            20000 non-null  float64
 7   final_price         20000 non-null  float64
 8   rating              20000 non-null  float64
 9   review_count        20000 non-null  int64
 10  stock               20000 non-null  int64
 11  seller_id           20000 non-null  str
 12  seller_rating       20000 non-null  float64
 13  purchase_date       20000 non-null  str
 14  shipping_time_days  20000 non-null  int64
 15  location            20000 non-null  str
 16  device              20000 non-null  str
 17  payment_method      20000 non-null  str
 18  is_returned         20000 non-null  bool
 19  delivery_status     20000 non-null  str
dtypes: bool(1), float64(5), int64(3), str(11)
memory usage: 3.1 MB

In [17]:
df.describe()

,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days
count,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000,20000.000000
mean,13321.073583,28.811396,10011.772449,3.923140,32.263600,250.877900,3.737465,3.145750
std,18143.304034,14.556562,14285.031791,0.521787,42.750803,144.939877,0.721338,1.660254
min,200.140000,5.010000,106.090000,2.100000,0.000000,0.000000,2.500000,1.000000
25%,2713.647500,16.757500,1724.700000,3.600000,10.000000,125.000000,3.100000,2.000000
50%,4969.405000,27.945000,3818.310000,3.900000,19.000000,252.000000,3.700000,3.000000
75%,14248.432500,39.080000,10473.885000,4.300000,38.000000,378.000000,4.400000,5.000000
max,79937.430000,69.990000,74962.480000,5.000000,1183.000000,500.000000,5.000000,6.000000

In [18]:
df.isnull().sum()

user_id               0
product_id            0
category              0
subcategory           0
brand                 0
price                 0
discount              0
final_price           0
rating                0
review_count          0
stock                 0
seller_id             0
seller_rating         0
purchase_date         0
shipping_time_days    0
location              0
device                0
payment_method        0
is_returned           0
delivery_status       0
dtype: int64