In [1]:
import pandas as pd

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler
)

from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(
    "../data/processed/featured_delivery_data.csv"
)

In [3]:
df.head()

,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days,location,payment_method,delivery_status,high_rating,fast_shipping,popular_product
0,Sports,Cycling,Nike,13307.41,24.89,9995.09,3.2,26,308,3.5,4,Mumbai,UPI,0,0,0,0
1,Electronics,Headphones,Samsung,5464.82,15.70,4606.69,3.1,5,453,2.7,4,Mumbai,Cash on Delivery,1,0,0,0
2,Beauty,Makeup,Lenovo,3437.74,45.41,1876.51,3.7,41,222,3.5,2,Hyderabad,Debit Card,1,0,1,0
3,Home,Kitchen,H&M,7754.11,14.21,6652.29,4.1,128,479,2.9,4,Hyderabad,UPI,0,1,0,1
4,Clothing,Men,Apple,967.17,30.44,672.76,3.9,18,471,3.3,5,Delhi,Credit Card,1,0,0,0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   category            20000 non-null  str
 1   subcategory         20000 non-null  str
 2   brand               20000 non-null  str
 3   price               20000 non-null  float64
 4   discount            20000 non-null  float64
 5   final_price         20000 non-null  float64
 6   rating              20000 non-null  float64
 7   review_count        20000 non-null  int64
 8   stock               20000 non-null  int64
 9   seller_rating       20000 non-null  float64
 10  shipping_time_days  20000 non-null  int64
 11  location            20000 non-null  str
 12  payment_method      20000 non-null  str
 13  delivery_status     20000 non-null  int64
 14  high_rating         20000 non-null  int64
 15  fast_shipping       20000 non-null  int64
 16  popular_product     20000 non-null  int64
dtypes: float64(5), int64(7), str(5)
memory usage: 2.6 MB

Encoding

In [5]:
le = LabelEncoder()

Selecting columns to encode

In [6]:
categorical_columns = [
    "category",
    "subcategory",
    "brand",
    "location",
    "payment_method"
]

In [7]:
for col in categorical_columns:
    df[col] = le.fit_transform(df[col])

In [8]:
df.head()

,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days,location,payment_method,delivery_status,high_rating,fast_shipping,popular_product
0,4,1,7,13307.41,24.89,9995.09,3.2,26,308,3.5,4,4,3,0,0,0,0
1,2,6,9,5464.82,15.70,4606.69,3.1,5,453,2.7,4,4,0,1,0,0,0
2,0,10,6,3437.74,45.41,1876.51,3.7,41,222,3.5,2,3,2,1,0,1,0
3,3,8,3,7754.11,14.21,6652.29,4.1,128,479,2.9,4,3,3,0,1,0,1
4,1,11,1,967.17,30.44,672.76,3.9,18,471,3.3,5,2,1,1,0,0,0

Creating x(Features) and y(Target) columns

In [9]:
X = df.drop("delivery_status", axis=1)

y = df["delivery_status"]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

Scaling

In [11]:
scaler = StandardScaler()

In [12]:
X_train = scaler.fit_transform(X_train)

In [13]:
X_test = scaler.transform(X_test)

In [14]:
X_train.shape

(16000, 16)

In [15]:
X_test.shape

(4000, 16)

In [16]:
df.head()

,category,subcategory,brand,price,discount,final_price,rating,review_count,stock,seller_rating,shipping_time_days,location,payment_method,delivery_status,high_rating,fast_shipping,popular_product
0,4,1,7,13307.41,24.89,9995.09,3.2,26,308,3.5,4,4,3,0,0,0,0
1,2,6,9,5464.82,15.70,4606.69,3.1,5,453,2.7,4,4,0,1,0,0,0
2,0,10,6,3437.74,45.41,1876.51,3.7,41,222,3.5,2,3,2,1,0,1,0
3,3,8,3,7754.11,14.21,6652.29,4.1,128,479,2.9,4,3,3,0,1,0,1
4,1,11,1,967.17,30.44,672.76,3.9,18,471,3.3,5,2,1,1,0,0,0